# Generated by Django 5.1.4 on 2025-02-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=125)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('link_drive', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=100, unique=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutorPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcastAutores', to='radioVirgen.autor')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoresPodcast', to='radioVirgen.podcast')),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='radioVirgen.programa'),
        ),
        migrations.AddField(
            model_name='autor',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='radioVirgen.programa'),
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcastReproduccion', to='radioVirgen.podcast')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioReproduccion', to='radioVirgen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPodcastPendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaPendientes', to='radioVirgen.programa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPendientes', to='radioVirgen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LikePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaLike', to='radioVirgen.programa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioLikePro', to='radioVirgen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LikePodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcastLike', to='radioVirgen.podcast')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioLikePod', to='radioVirgen.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.CheckConstraint(condition=models.Q(('categoria__in', ['Educativo', 'Comedia', 'Formación'])), name='check_categoria_values'),
        ),
    ]
