# Generated by Django 5.1.4 on 2025-02-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioVirgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapodcastpendientes',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcastPendientes', to='radioVirgen.programa'),
        ),
    ]
