# Generated by Django 5.1.4 on 2025-02-21 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioVirgen', '0003_remove_listapodcastpendientes_programa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('numTarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('nombreTitular', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('numCuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('tlf', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['Tarjeta', 'PayPal', 'Transferencia', 'Bizum'])), name='check_tipo_pago_values')],
            },
        ),
        migrations.CreateModel(
            name='UsuariosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.BooleanField(default=False)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodoUsuario', to='radioVirgen.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioMetPago', to='radioVirgen.usuario')),
            ],
        ),
    ]
