# Generated by Django 5.1.4 on 2025-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioVirgen', '0004_metodopago_usuariospago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='cvc',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombreTitular',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='numCuenta',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='numTarjeta',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tlf',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
